# Generated by Django 4.2.6 on 2023-11-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_username_user_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='file',
            field=models.FileField(default=3, upload_to=''),
            preserve_default=False,
        ),
    ]
