# Generated by Django 4.2.6 on 2023-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_info_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='file',
            field=models.FileField(upload_to='FILES'),
        ),
    ]
